global:
  resolve_timeout: 5m
route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 30s
  repeat_interval: 15m
  receiver: 'telegram'
  routes:

  - match:
      alertname: InstanceDown
    receiver: telegram

  - match:
      alertname: Elasticsearch disk out of space
    receiver: telegram
  
  - match:
      alertname: DiskSpaceFree10Percent
    receiver: telegram

  - match:
      alertname: RAMUsageFree20Percent
    receiver: telegram
  
  - match:
      alertname: Prometheus target missing
    receiver: telegram

  - match:
      alertname: Prometheus all targets missing
    receiver: telegram

receivers:
- name: 'telegram'
  webhook_configs:
  - url: http://178.154.222.98:9119/alert
    send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
