version: "3.7"


volumes:
  postgres_data:

services:

  flask:
    image: flask
    environment:
      - DB_CONNECTION=postgresql://postgre:postgre@db:5432/postgre
    restart: unless-stopped
    build:
      context: /home/lysenko/
      dockerfile: Dockerfile
    ports:
      - 8080:5000
    depends_on:
      - db
    command: bash -c "flask db init && flask db migrate && flask db upgrade&& flask run --host=0.0.0.0"

  db:
    image: postgres:12.2-alpine
    env_file:
      - ./postgres-develop.env
    ports:
      - "5432:5432"

  postgres-exporter:
    container_name: postgres-exporter
    hostname: postgres-exporter
    image: wrouesnel/postgres_exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://postgre:postgre@db:5432/postgre?sslmode=disable"
    ports:
      - "9187:9187"
    restart: unless-stopped   
